security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user:
            id: App\Infrastructure\Security\Provider\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # by default, the feature allows 5 login attempts per minute
            pattern: /admin
            login_throttling: ~
            lazy: true
            provider: user
            form_login:
                login_path: admin_login
                check_path: admin_login
                enable_csrf: true
                username_parameter: email
                password_parameter: password
            logout:
                path: admin_logout
                target: admin_login
    access_control:
        - { path: ^/admin/auth, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: "plaintext"
